services:
  - type: web
    name: amount-collector-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_NAME
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BACKEND_CORS_ORIGINS
        value: "*"
